<?php
/**
 * Core module — capabilities, roles, health.
 *
 * @package DMF
 */

namespace DMF\Modules\Core;

use DMF\Modules\AbstractModule;

defined( 'ABSPATH' ) || exit;

/**
 * Owns the shared `dmf_listing` capability set and the framework roles.
 */
final class CoreModule extends AbstractModule {

	/**
	 * Capabilities generated by capability_type=dmf_listing + map_meta_cap.
	 *
	 * @return string[]
	 */
	private function capabilities(): array {
		return array(
			'edit_dmf_listing',
			'read_dmf_listing',
			'delete_dmf_listing',
			'edit_dmf_listings',
			'edit_others_dmf_listings',
			'publish_dmf_listings',
			'read_private_dmf_listings',
			'delete_dmf_listings',
			'delete_private_dmf_listings',
			'delete_published_dmf_listings',
			'delete_others_dmf_listings',
			'edit_private_dmf_listings',
			'edit_published_dmf_listings',
		);
	}

	public function install(): void {
		// Administrators and editors manage listings.
		foreach ( array( 'administrator', 'editor' ) as $role_key ) {
			$role = get_role( $role_key );

			if ( $role ) {
				foreach ( $this->capabilities() as $cap ) {
					$role->add_cap( $cap );
				}
			}
		}

		// Destination Partner: a member who manages ONLY their own listings.
		add_role(
			'dmf_partner',
			__( 'Destination Partner', 'dmf' ),
			array(
				'read'                 => true,
				'upload_files'         => true,
				'edit_dmf_listing'     => true,
				'read_dmf_listing'     => true,
				'delete_dmf_listing'   => true,
				'edit_dmf_listings'    => true,
				'delete_dmf_listings'  => true,
			)
		);
	}
}
